services:

  api:
    image: maven:3.9.6-amazoncorretto-17
    command: mvn spring-boot:run
    restart: always
    working_dir: /api
    container_name: api
    volumes:
      - ~/.aws/:/root/.aws
      - ./api:/api
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_started
      db:
        condition: service_started
      redis:
        condition: service_started
      localstack:
        condition: service_started
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network

  db:
    image: postgres:13.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./api/tmp/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - network

  redis:
    image: redis/redis-stack
    container_name: redis
    volumes:
      - ./api/tmp/redis:/var/lib/redis/data
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - network

  localstack:
    image: localstack/localstack
    container_name: localstack
    user: root
    environment:
      - SERVICES=s3,ses
      - DEFAULT_REGION=us-east-1
    ports:
      - 4566:4566
    env_file:
      - .env
    volumes:
      - ./infrastructure/init_localstack_infra.sh:/etc/localstack/init/ready.d/init_localstack_infra.sh
    networks:
      - network

networks:
  network:
    driver: bridge
